Add full table of content
- Change the generate script to add a custom style
- Fix some errors in the documentation
- Add reCompile as a function to optimize regular expression substitutions (avoid compile multiple times)
- Add RealName to FuncInfo to get the real name of alias functions (required to link to the correct anchor)
- Update the web theme

diff --git a/render-doc b/render-doc
--- a/render-doc
+++ b/render-doc
@@ -9,9 +9,27 @@ export COLUMNS=108
 rm -rf $DOC_FOLDER
 mkdir -p $DOC_FOLDER
 
+git submodule update --init
+
+echo '
+.flink {
+    display: inline-block;
+    min-width: 2.5in;
+}
+' > docs/themes/book/assets/_custom.scss
+
 # Generate usage info
-printf -- '---\ntitle: CLI Usage\nweight: 1\n---'  > $DOC_FOLDER/CLI_Usage.md
-./gotemplate '```text@<trim(exec("./gotemplate -h"))@<;```' --nv >> $DOC_FOLDER/CLI_Usage.md
+./gotemplate '@-
+---
+title: CLI Usage
+weight: 1
+---
+<!-- markdownlint-disable MD025 --->
+# CLI Usage
+
+```text
+@trim(exec("./gotemplate -h"))
+```' --nv > $DOC_FOLDER/CLI_Usage.md
 
 # Add basics section
 mkdir -p $DOC_FOLDER/basic_features
@@ -30,7 +48,7 @@ rsync -av docs_tests/ $DOC_FOLDER -r
 # Generate detailed function info
 ./gotemplate --no-extension --color '
 @-define("trim")
-    @{wrapped} := String(text).Replace("<", "&lt;").Wrap(95)
+    @{wrapped} := String(text).Replace("<", "&lt;").Wrap(69)
     @-if (indent)
         @{wrapped} = $wrapped.IndentN(indent).TrimSpace()
     @-end if
@@ -38,14 +56,16 @@ rsync -av docs_tests/ $DOC_FOLDER -r
 @-end define
 
 @-define("GenerateCategory")
-    @-print("# ", regexReplaceAll(`(?P<name>.*), (?P<url>http://.*)`, category.Name, `[${name}](${url})`))
+    @{re} := reCompile(`(?P<name>.*), (?P<url>http://.*)`)
+    @-println("---\nbookToC: 2\nweight: 2\n---")
+    @-print("# ", re.ReplaceAllString(category.Name, `[${name}](${url})`))
     @<print("<!-- markdownlint-disable MD033 MD024 --->")
     @-foreach ($func := category.Functions())
-        @{func} := function($func)
+        @{func} = function($func)
         @-if (!$func.IsAlias)
             @<printf("\n## __%s__\n", $func.Name)
             @<print("```go")
-            @<println("func", stripColor($func.Signature))
+            @<println("func", include("trim", dict("text", stripColor($func.Signature))))
             @-print("```")
             @-if ($func.Description)
                 @<print("\n<pre>")
@@ -73,13 +93,33 @@ rsync -av docs_tests/ $DOC_FOLDER -r
 @end define
 
 @-completeExamples()
+@{re} := reCompile(`(?P<name>.*), http://.*`)
+
 @-foreach ($category := categories())
     @{content} := include("GenerateCategory", merge(dict("category", $category), $))
-    @{name} := regexReplaceAll(`(?P<name>.*), http://.*`, $category.Name, `${name}`)
+    @{name} := $re.ReplaceAllString($category.Name, `${name}`)
     @-info("Generating documentation for", $name)
     @-save(joinPath(folder, lower($name))+".md", $content)
 @--end foreach' -Vfolder=$DOC_FOLDER/functions_reference
 printf -- '---\nbookFlatSection: true\nweight: 4\n---' > $DOC_FOLDER/functions_reference/_index.md
+
+./gotemplate --no-extension '
+@-println("---\nweight: 1\n---")
+@<print("<!-- markdownlint-disable MD033 --->")
+
+@{re} := reCompile(`(?P<name>.*), http://.*`)
+@{reClean} := reCompile(`[^\w]+`)
+@<print("# All functions")
+@-foreach ($category := categories())
+    @{categoryName} := $re.ReplaceAllString($category.Name, `${name}`)
+    @<println("\n##", $categoryName)
+    @{categoryName} = $reClean.ReplaceAllString(lower($categoryName), `-`)
+    @-foreach ($func := $category.Functions())
+        @{func} = function($func)
+        @<printf(`<span class="flink"><a href="/gotemplate/docs/functions_reference/%s#%s">%s</a></span>`, $categoryName, lower($func.RealName), $func.Name)
+    @-end foreach
+@--end foreach
+' > $DOC_FOLDER/functions_reference/all_functions.md
 
 # Add structs documentation
 mkdir -p $DOC_FOLDER/objects
@@ -92,3 +132,13 @@ printf -- '---\nbookFlatSection: true\nweight: 5\n---' > $DOC_FOLDER/objects/_in
 # Copy README as the main page
 printf -- '---\ntype: docs\n---' > $CONTENT_FOLDER/_index.md
 cat README.md >> $CONTENT_FOLDER/_index.md
+
+if [ "$1" == serve ]
+then
+    trap quit EXIT
+    function quit() {
+        # Cleanup the imported module since we changed custom CSS
+        git submodule deinit -f docs/themes/book
+    }
+    (cd docs && hugo server)
+fi
